### ISSUE TITLE
Experimental Results

### ISSUE THREAD

**Issue by baldas** [andrefaraujo/videosearch#19]
Hi Andre, thanks for the great work and for make the code available. This is not a code issue, but rather some questions about the last table (Table V) of your IEEE TCSVT article. In particular, the questions are about how some of the parameters were measured (I have used the 600k version of the SI2V dataset for my initial experiments):

1) For mAP, I see that the scripts available in the /scoring/ directory already display the final scores. Are those the values you used in the article?

2) For the latency, I also see some output displayed when the queries scripts are executed. Did you just take the average of all the queries? I got somewhat different results with my machine compared to the ones in Table V. For instance, results for the frame-based and scene-based approaches were, on average, 6.2s and 0.5s, respectively. For the bloom filter approach I have no idea how to measure the latency, since the retriever script works in a different manner. How did you measure the latency for the BF-PI approach?

3) Finally, I guess the memory column (Table V) refers to the file size of the joined global descriptors of each approach, am I right? For the bloom filter approach, however, I am not sure how to calculate that because there is no 'join' script. How did you measure the memory results for the BF-PI approach?

Thanks!

**Comment by andrefaraujo** [comment]
Hi @baldas , apologies for the delay in responding. 

1. Yes.

2. I think the latency you measured refers to the one measured [here](https://github.com/andrefaraujo/videosearch/blob/master/retriever/retriever.cc#L286), right? This measurement includes query global descriptor extraction, while the latency in Table V actually only refers to the database search latency. You can read more details on how the latency is computed in my [PhD thesis](https://searchworks.stanford.edu/view/11739291), see specifically page 99 under "Retrieval Latency".

3. Please also refer to the PhD thesis link mentioned above, specifically page 100 under "Index size".

In general, the PhD thesis mentioned above contains a lot more details on these experiments. Due to the TCSVT page limit, we had to shorten explanations considerably. So I would recommend you to look into it once you have detailed questions like this.

Hope this helps, let me know if there are any follow-up questions.

**Comment by baldas** [comment]
Thanks a lot. I will certainly take a look at your thesis.
